### ISSUE TITLE
 Congratulations

### ISSUE THREAD

**Issue by josejachuf** [emmett-framework/rest#1]
Thank you. Excellent work.
I am a user of weppy-REST and I see, in a first quick read, that emmett-REST already solves almost all the common situations in which you had to write a little more code in w-rest. I'm going to try it more carefully in some app that I have working.

The first thing that caught my attention were the queries and additional routes

regards

**Comment by gi0baro** [comment]
@josejachuf thank you.

If you have any feedbacks, objections, critics about the implementation, the syntax, the docs, or you think I can improve the project in different ways, please share them :)
