### ISSUE TITLE
About query language

### ISSUE THREAD

**Issue by josejachuf** [emmett-framework/rest#17]
Hi @gi0baro 
I am trying to use where with **$or** and **$and** but it doesn't work as I hope

in javascript I have:

```
if (params.filter) {
    where = {
      $or: [
        {
          // id: params.filter,
          last_name: { $ilike: params.filter },
          first_name: { $ilike: params.filter }
        }
      ]
    }
    where = JSON.stringify(where)    
  }
```
With this I get, for example:

`{"$or":[{"last_name":{"$ilike":"Fue"},"first_name":{"$ilike":"Fue"}}]}`

then:
`http://a.com/api/user?page=1&page_size=20&sort_by=-id&where={"$or":[{"last_name":{"$ilike":"F"},"first_name":{"$ilike":"F"}}]}`

but not returns data

What am I doing wrong?
Jose

**Comment by josejachuf** [comment]
This work:
`where = { last_name: { $ilike: '%' + params.filter + '%' } }`

the % were missing, but with **$or** not works:

```
 where = {
      $or: [
        {
          // id: params.filter,
          last_name: { $ilike: '%' + params.filter + '%' },
          first_name: { $ilike: '%' + params.filter + '%' }
        }
      ]
    }
```

**Comment by gi0baro** [comment]
@josejachuf the list argument of `$or` should contain the objects of the conditions:

```javascript
where = {
  $or: [
    {last_name: { $ilike: '%' + params.filter + '%' }},
    {first_name: { $ilike: '%' + params.filter + '%' }}
  ]
}
```

while you put a single object, so a single AND condition.

Also, you probably want to swtich from `$ilike` to `$icontains`.

**Comment by josejachuf** [comment]
Thanks, works fine!!
