### ISSUE TITLE
upgrade requirements.txt

### ISSUE THREAD

**Issue by josejachuf** [emmett-framework/rest#2]
Hi @gi0baro , 
upgrade is needed so that it doesn't protest the version of emmett

**Comment by gi0baro** [comment]
@josejachuf you right, just published 1.0.0a2

**Comment by josejachuf** [comment]
@gi0baro 
The same, with the change of version of emmett the dependency of rest is broken

**Comment by gi0baro** [comment]
@josejachuf with 1.0.0b1 should be fixed definitely.
