### ISSUE TITLE
Using cache

### ISSUE THREAD

**Issue by josejachuf** [emmett-framework/rest#20]
Hi @gi0baro, 

Is there any way to use cache without explicitly defining index and read methods?

**Comment by gi0baro** [comment]
@josejachuf I'm afraid not.

In my experience caching plays quite bad with RESTFul APIs, as the additional complexity needed to clear caches (every time you get a POST/PUT/DELETE you should clear the involved caches) generally makes it not worth the candle.

You can still define index and read one time in a custom `RESTModule` subclass and re-use it on all the modules you want the cache on.

**Comment by josejachuf** [comment]
I understand,. Thanks @gi0baro
