### ISSUE TITLE
Help with Query Language

### ISSUE THREAD

**Issue by josejachuf** [emmett-framework/rest#21]
Hi, 

This works:
`http://localhost:8000/main/api/v1/myapy?where={"myfield": "Carlos"}`

Returns to me the records that meet the condition.

This does not work, nothing returns me:
`http://localhost:8000/main/api/v1/myapy?where={"myfield": { "$ilike": "%Carlos%" }}`

```
{
  "data": [],
  "meta": {
    "object": "list",
    "has_more": false,
    "total_objects": 0
  }
}
```

In an older version of Emmett and Emmett Rest something like this did work
`
$or: [{ myfield: { $ilike: "%Carlos%" }}, {another_field: { $ilike: "%Carlos%" }}]`

**Comment by gi0baro** [comment]
@josejachuf does it work with `"$icontains"`?

**Comment by josejachuf** [comment]
Ok, I try it and I tell you.
Thanks

**Comment by josejachuf** [comment]
> @josejachuf does it work with `"$icontains"`?

This works fine!
