### ISSUE TITLE
Deprecated notification with emmet 2.1

### ISSUE THREAD

**Issue by josejachuf** [emmett-framework/rest#4]
Hi @gi0baro 

> /venv/lib/python3.8/site-packages/emmett_rest/ext.py:59: RemovedInNextVersionWarning: extensions.listen_signal str argument is deprecated, use extensions.Signals as argument instead.
>   @listen_signal('before_database')
> 

Jose

**Comment by josejachuf** [comment]
Hi
I tried to make a pull request with the patch, but I get an email with the message that it doesn't pass the tests. Well, just that. I hope you are good

**Comment by gi0baro** [comment]
@josejachuf thank you, unfortunately it's failing due to tests code that has to be ported to 2.1.. will check on this in the next days
